# Generated by Django 4.2.7 on 2023-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_hora',
            field=models.DateTimeField(verbose_name='Data e hora'),
        ),
        migrations.AlterField(
            model_name='local',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
    ]
